### ISSUE TITLE
gentoo

### ISSUE THREAD

**Issue by imyxh** [Arinerron/Game#6]

**Comment by imyxh** [comment]
idk like you have this on the aur but what about gentoo???????????
according to this tux kid gentoo is like the os of the gods or something

**Comment by amelanoleuca** [comment]
gentoo users don't need a central repository to install packages

**Comment by Arinerron** [comment]
bug fixed in commit 24ef315521a9da3bbafdd0943717da892e4df700

**Comment by Arinerron** [comment]
pls give current coordinates to send bug bounty to for critical bug thanks

**Comment by imyxh** [comment]
@Arinerron of course! I'm at `38.8170, -77.1678`
